apiVersion: v1
kind: ConfigMap
metadata:
  name: product-search-config
data:
  OTEL_EXPORTER_OTLP_ENDPOINT: "http://prometheus-stack-kube-prom-prometheus.monitoring:9090" 
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-search-app
  labels:
    app: product-search
spec:
  replicas: 3
  selector:
    matchLabels:
      app: product-search
  template:
    metadata:
      labels:
        app: product-search
    spec:
      containers:
      - name: product-search-app
        image: vunt94/product-search-app:latest
        ports:
        - containerPort: 8000
        resources:
          requests:
            memory: "1Gi"
            cpu: "250m"
          limits:
            memory: "4Gi"
            cpu: "1000m"
        volumeMounts:
        - name: pinecone-secret-volume
          readOnly: true
          mountPath: "/etc/pinecone-secrets"
---
apiVersion: v1
kind: Service
metadata:
  name: product-search-service
spec:
  selector:
    app: product-search
  ports:
    - name: api-port
      protocol: TCP
      port: 80
      targetPort: 8000
  type: ClusterIP