apiVersion: v1
kind: Secret
metadata:
  name: pinecone-api-key
type: Opaque
data:
  PINECONE_API_KEY_B64: cGNza180NmtYVDdfMzZkZUZCVFY3Szc0QU5oSjZnRGNwTnZBVVFweTlvMThwTnhWR3JIdVZFU1NBcG5tRnJnODFTS0pLQmtNS0RSbXktYXBw